define('tours_page_amd/init_team_page_v2',['jquery','common_amd/tool'],function($,tool){var exports={};function doAddCompare(){$("#addToComp").mouseenter(function(){var isNormal=$(this).hasClass("bg_compare_normal");if(isNormal){$(this).removeClass("bg_compare_normal");$(this).addClass("bg_compare_hover");}}).mouseleave(function(){var isHover=$(this).hasClass("bg_compare_hover");if(isHover){$(this).removeClass("bg_compare_hover");$(this).addClass("bg_compare_normal");}});}
function doAddCollection(){$(document).ready(function(){var url2="http://www.tuniu.com/yii.php?r=api/attention/isAttention";$.ajax({url:url2,dataType:"jsonp",jsonp:"callFuc",data:{routeId:$("#route_id_tmp").val()},success:function(data){$("#favorite_id").removeClass("bg_focus_normal bg_focus_click");switch(data){case 1:$("#favorite_id").addClass("bg_focus_normal");$("#favorite_id").text("关注");break;case 2:$("#favorite_id").addClass("bg_focus_click");$("#favorite_id").text("已关注");break;case 4:$("#favorite_id").addClass("bg_focus_normal");$("#favorite_id").text("关注");break;}}});});$(window).on("bg_focus_clicked bg_box_foucs_clicked",function(e){var target=$("#focus_num");var offset=$(target).offset();var oneElt=$("<div></div>").addClass("plus_one").css({top:offset.top-$(window).scrollTop(),left:offset.left+(($(target).width()-24)/2)});$(document.body).append(oneElt);$(oneElt).animate({top:"-=30"}).fadeOut(function(){$(oneElt).remove();});});$("#favorite_id").mouseenter(function(){var isNormal=$(this).hasClass("bg_focus_normal");if(isNormal){$(this).removeClass("bg_focus_normal");$(this).addClass("bg_focus_hover");}}).mouseleave(function(){var isHover=$(this).hasClass("bg_focus_hover");if(isHover){$(this).removeClass("bg_focus_hover");$(this).addClass("bg_focus_normal");}});$("#favorite_id").click(function(){var routeId=$("#route_id_tmp").val();if($(this).hasClass("bg_focus_click")){$('#delete_collcet_id').show();$('#collcet_id').hide();return;}
var url="http://www.tuniu.com/yii.php?r=api/attention/attention";var days=$('#journeyDays').val();var departCityName=$('#departCityResult').attr('cityname');days=days==null?0:days;$.ajax({url:url,dataType:"jsonp",jsonp:"callFuc",data:{routeId:routeId,days:days,departCityName:departCityName},success:function(data){switch(data){case 1:disClick();$('#collcet_id').show();$('#delete_collcet_id').hide();break;case 2:break;case 3:alert('添加关注失败!');break;case 4:$('#login_id').show();break;}}});});}
function clickAddScroll(){var userId=$("#userId").attr("user_id"),routeId=$("#route_id_tmp").val();if(userId>0){var url="/main.php?do=user_route_collect&flag=collectInsert";var info={userId:userId,routeId:routeId};$.get(url,info,function(data){if(data==1){disClick();$('#collcet_id').show();$('#delete_collcet_id').hide();return;}else if(data==2){$('#delete_collcet_id').show();$('#collcet_id').hide();$(".add_to_favorite").removeClass("on");$(".change_price").children('div').removeClass('change_price_con').css('display','none');$('.start_subscribe').addClass('change_price_con');$('.change_plan_date').addClass('change_price_date');$('.change_price_list .subscribe_info').hide();$('.select_date1').find('.s_con').text('请选择出发日期');$('.select_date2').find('.s_con').text('请选择出发日期');$('.email').val('');return;}else if(data==3){alert('添加收藏失败!');return;}else if(data==4){alert('删除收藏失败!');return;}});}else{$('#login_id').show();return;}}
function request(paras){var url=location.href;var paraString=url.substring(url.indexOf("?")+1,url.length).split("&");var paraObj={}
for(i=0;j=paraString[i];i++){paraObj[j.substring(0,j.indexOf("=")).toLowerCase()]=j.substring(j.indexOf("=")+1,j.length);}
var returnValue=paraObj[paras.toLowerCase()];if(typeof(returnValue)=="undefined"){return"";}else{return returnValue;}}
function disClick(){var addBtn=$("#favorite_id");$(addBtn).trigger("bg_focus_clicked");$(addBtn).removeClass("bg_focus_hover");$(addBtn).addClass("bg_focus_click on");$(addBtn).text("已关注");var value=parseInt($("#focus_num").text());$("#focus_num").text(value+1);if($(addBtn).hasClass("on")){$(".add_scroll").addClass("addbtn");}}
function disUnclick(){var addBtn=$("#favorite_id");$(addBtn).removeClass("bg_focus_click on");$(addBtn).addClass("bg_focus_hover");}
function loadXmlDocRecentOrderInfo(url,func){if(window.XMLHttpRequest){xmlhttpRecentOrders=new XMLHttpRequest();}else{xmlhttpRecentOrders=new ActiveXObject("Microsoft.XMLHTTP");}
xmlhttpRecentOrders.onreadystatechange=func;xmlhttpRecentOrders.open("GET",url,true);xmlhttpRecentOrders.send();}
function mouseAsync(){if(document.getElementById("recent_orders_show")){callBackRecentOrderInfo();}}
var xmlhttpRecentOrders;function callBackRecentOrderInfo(){var routeId=$("#route_id_tmp").val();var empty_tenUsers=$("#empty_tenUsers").val();var urlRecentOrders="/lazy/routeRecentOrder/";urlRecentOrders+=routeId;loadXmlDocRecentOrderInfo(urlRecentOrders,function(){if(xmlhttpRecentOrders.readyState==4&&xmlhttpRecentOrders.status==200){document.getElementById("recent_orders_show").innerHTML=xmlhttpRecentOrders.responseText;if(!empty_tenUsers){if($(".ub_wrap").find("li").length>0){var marquee=new ScrollText("ub_wrap");marquee.LineHeight=30;marquee.Amount=1;marquee.Timeout=1000;marquee.Delay=30;marquee.Start();}}}});}
var init=function(){$('.update_project').each(function(i,n){$(this).hover(function(){$('.update_con').eq(i).toggle(0,function(){$('.update_project').eq(i).toggleClass('update_project_hover');return false;});});});if($('#kind_flag').length>0&&$('#tour_abstruct').length>0){if($('#kind_flag').val()==7){var cont=$.trim($('#tour_abstruct').text());cont=cont.substring(0,cont.length-1);$('#tour_abstruct').text(cont+'（您可在网上预订过程中查看和选择合适的航班出行）。');}}
var cmpId=request('cmpid');var routeId;var noDateStr=$('#no_product').val();var noDate=parseInt(noDateStr,10);var cityCode=$('#city_code').val();var catid=$('#catid').val();if(noDate==1){routeId=$('#route_id_tmp').val();}else{routeId=0;}
if(!cmpId){cmpId=0;}
if(cmpId=='mkt_08009601'||cmpId=='mkt_08009602'||noDate){var data={'key':'recommended','id':catid,'routeid':routeId,'city':cityCode,'type':1,'limit':4,'cmpid':cmpId};$.get('/ajax-default/',data,function(data,status){if(data){$("#noprod_box").html(data);$("#noprod_box").show();}else if(noDate==1){try{var arrPageSizes=___getPageSize();$('#noDate').css({top:parseInt($('#noDate').css("top"))-(arrPageSizes[3]/5)+(arrPageSizes[3]-parseInt($('#noDate').css("height")))/2-10});}catch(e){}
$("#noprod_box").removeClass("mb_10");}else{$("#noprod_box").removeClass("mb_10");}});}
$(document).one('mousemove',mouseAsync);$(function(){$('.pop_box .del').each(function(){$(this).click(function(){$(this).parent().hide();})});var userId=$('#userId').attr("user_id");var myCollectId=$('#myCollectId').attr("my_collect_id");if(userId>0&&myCollectId>0){disClick();}});doAddCollection();doAddCompare();};exports.init=init;return exports;});;define('tours_page_amd/online_ask',['jquery','common_amd/thickbox3.1'],function($,thickbox_mod){var exports={};var tb_show=thickbox_mod.tb_show;function getCookie(c_name)
{if(document.cookie.length>0)
{c_start=document.cookie.indexOf(c_name+"=")
if(c_start!=-1)
{c_start=c_start+c_name.length+1
c_end=document.cookie.indexOf(";",c_start)
if(c_end==-1)
c_end=document.cookie.length
return unescape(document.cookie.substring(c_start,c_end))}}
return""}
function getAskByType(page){var type=$("#page_num").val();if(page){curPage=page;}else{curPage=1;}
if($(".aq_search_input").val()!="请输入问题"){searchContent=$(".aq_search_input").val();}else{searchContent='';}
routeId=$('#online_ask_route_id').val();var url="/yii.php?r=knowledgeAsk/index/";var askdata="&page="+curPage+"&type="+type+"&routeId="+routeId+"&search="+searchContent;$.post(url,askdata,function(data){var consul_list=data.consul_list;var consul_pager=data.pager;if(typeof(consul_list)=="undefined"||consul_list==''){$('.all_question').hide();$('#show_no_question').show();}else{$('.all_question').show();$('#show_no_question').hide();document.getElementById("consul_pager").innerHTML=consul_pager;if(consul_pager=="<span class='page-cur'>1</span>"){$('#pagination').hide();}else{$('#pagination').show();}
var list_num=consul_list.length;var li_list=$('.all_question .AQ_ques').find("li");li_list.css("display","none");for(var i=0;i<list_num;i++){cul_tmp=consul_list[i];li_tmp=li_list.eq(i);li_tmp.css("display","");if(cul_tmp.common_flag==1){li_tmp.find('.AQ_left_ask').html('');li_tmp.find('.AQ_left_ask').prepend('<span class="c_icon">常见问题</span>咨询内容:');}else{li_tmp.find('.AQ_left_ask').html('');li_tmp.find('.AQ_left_ask').prepend('<span class="q_icon">咨询内容：</span>');}
var askurl="/asks/";askurl=askurl+cul_tmp.id;li_tmp.find('.a_qst').attr("href",askurl);li_tmp.find('.a_time').text(cul_tmp.adddate);li_tmp.find('.a_con').text(cul_tmp.answer);li_tmp.find('.a_qst').text(cul_tmp.content);}}},'json');}
function show_login(pars,login_func,tel_func){var ssoLoginFlag=document.getElementById('ssoLoginFlag');if(typeof(ssoLoginFlag)=="undefined"||ssoLoginFlag==null){var url="/yii.php?r=quickLogin/index/loginType/";url+=pars;url+="&placeValuesBeforeTB="+'savedValues';url+="&TB_iframe="+true;url+="&height="+250;url+="&width="+650;url+="&modal="+true;tb_show('',url,'');}else{var url='/yii.php?r=ssoConnect/checkloginStatus';$.get(url,function(data){if(data==0){var str=window.location.host;var domain=str.split(".")[0];if($.layer&&typeof($.layer)=="function"){$.layer({type:2,title:false,shadeClose:true,closeBtn:[1,true],iframe:{src:'https://passport.tuniu.com/login/iframe?origin='+encodeURIComponent('http://www.tuniu.com/ssoConnect/Iframe?reload='+domain)},area:['375px','350px']});}else{var url="/yii.php?r=quickLogin/index/loginType/";url+=pars;url+="&placeValuesBeforeTB="+'savedValues';url+="&TB_iframe="+true;url+="&height="+250;url+="&width="+650;url+="&modal="+true;tb_show('',url,'');}}else{if($.layer&&typeof($.layer)=="function"){layer.alert("您已登录，将帮你自动刷新页面！");}
window.location.reload();}});}}
function check_data(){tuniuUserCookie=getCookie("tuniuuser");if(tuniuUserCookie==""){pars="ask";show_login(pars,'','');return false;}
var selectRadio=document.getElementsByName("aq_style");for(var i=0;i<selectRadio.length;i++){if(selectRadio[i].checked){question_type=selectRadio[i].value;}}
$("#sub_button").attr('disabled',true);if(typeof(question_type)=="undefined"){document.getElementById("choose_question").style.display="block";$("#sub_button").removeAttr('disabled');return false;}
if(document.getElementById("ask_content").value==""){document.getElementById("write_question").style.display="block";document.getElementById("ask_content").focus();$("#sub_button").removeAttr('disabled');return false;}
if(document.getElementById("email").value!=''){if(document.getElementById("email").value.search(/^\w+((-\w+)|(\.\w+))*\@[A-Za-z0-9]+((\.|-)[A-Za-z0-9]+)*\.[A-Za-z0-9]+$/)==-1){alert("请填写正确邮箱");document.getElementById("email").focus();$("#sub_button").removeAttr('disabled');return false;}}
if(document.getElementById("identify").value==""){document.getElementById("write_identify").style.display="block";document.getElementById("identify").focus();$("#sub_button").removeAttr('disabled');return false;}
var identify=document.getElementById("identify").value;var result=$.get("/main.php?do=user_reg_check_name&identify="+identify+"&flag=single_identify&cache="+Math.random(),function(data){identify_check_result(data)});return false;}
function change_img(){var random=Math.random();var imageCode=$('#identify_img');if(imageCode.length>0){imageCode[0].src='/identify.php?sid='+random;}}
function load_code(){var identify_img=$("#identify_img");if(identify_img.length>0){if(identify_img.css('display')=='none'){identify_img.show();var random=Math.random();identify_img[0].src='/identify.php?sid='+random;}}}
function identify_check_result(result){routeId=$('#online_ask_route_id').val();if(result=='1'){var url='/tours/addask/'+routeId;var user_email=$("#email").val()
if(''==$("#email").val()){user_email=$("#user_email").val();}
var selectRadio=document.getElementsByName("aq_style");for(var i=0;i<selectRadio.length;i++){if(selectRadio[i].checked){question_type=selectRadio[i].value;}}
var info={content:$("#ask_content").val(),email:user_email,identify:$("#identify").val(),question_type:question_type};$.post(url,info,function(data){if(data==-1){alert('验证码填写错误');change_img();$("#sub_button").removeAttr('disabled');}else if(data==-2){alert('问题字数不能超过200字');change_img();$("#sub_button").removeAttr('disabled');}else if(data==-3){alert('请填入问题的内容');change_img();$("#sub_button").removeAttr('disabled');}else if(data==-4){alert('请填入邮箱地址');change_img();$("#sub_button").removeAttr('disabled');}else if(data==0){alert('提交失败，请重试');change_img();$("#sub_button").removeAttr('disabled');}else if(data==1){alert('您的提问已提交成功，感谢您的关注。您的提问我们会在30分钟内回复。\n18:00之后的提问将在次日9：00后回复。您也可以登录会员中心-我的提问中查看您的问题及回复。');$("#sub_button").removeAttr('disabled');$("#ask_content").val('');$("#identify").val('');for(var i=0;i<selectRadio.length;i++){if(selectRadio[i].checked){selectRadio[i].checked=false;}}}});}else{alert('验证码填写错误');change_img();$("#sub_button").removeAttr('disabled');}}
var init=function(){thickbox_mod.init();$(function(){$(".aq_list .cj_pro").click(function(){$(this).addClass("curr").siblings().removeClass("curr");$("#page_num").val("");$("#pagination").hide();$(".all_question .cj_pro").show();$(".all_question .AQ_ques").hide();})
page_pro();function page_pro(){var last_index=1;var pagesLen=$(".cj_pro_page .page_num");pagesLen.click(function(){var i=$(this).index();if(i>1){$(".page_prev").show();}else{$(".page_prev").hide();}
$(this).addClass("page-cur").siblings().removeClass("page-cur");$(".cj_pro li").hide();$(".cj_pro").find("li.page_"+i).show();last_index=i;if(i==4){$(".page_next").hide();}else{$(".page_next").show();}});$(".page_next").click(function(){last_index++;$(".page_prev").show();if(last_index==4){pagesLen.eq(3).addClass("page-cur").siblings().removeClass("page-cur");$(".page_next").hide();$(".cj_pro li").hide();$(".cj_pro").find("li.page_4").show();}else{$(".page_next").show();pagesLen.eq(last_index-1).addClass("page-cur").siblings().removeClass("page-cur");$(".cj_pro li").hide();$(".cj_pro").find("li.page_"+last_index).show();}});$(".page_prev").click(function(){last_index--;$(".page_next").show()
if(last_index==1){pagesLen.eq(0).addClass("page-cur").siblings().removeClass("page-cur");$(".page_prev").hide();$(".cj_pro li").hide();$(".cj_pro").find("li.page_1").show();}else{$(".page_prev").show();pagesLen.eq(last_index-1).addClass("page-cur").siblings().removeClass("page-cur");$(".cj_pro li").hide();$(".cj_pro").find("li.page_"+last_index).show();}});}
$(".aq_list a").bind({click:clickCurr});function clickCurr(){$(".all_question .cj_pro").hide();$(".all_question .AQ_ques").show();$(this).addClass("curr").siblings().removeClass("curr");$("#page_num").val($(this).attr("value"));var type=$("#page_num").val();var curPage=1;if($(".aq_search_input").val()!="请输入问题"){searchContent=$(".aq_search_input").val();}else{searchContent='';}
routeId=$('#online_ask_route_id').val();var url="/yii.php?r=knowledgeAsk/index/";var askdata="&page="+curPage+"&type="+type+"&routeId="+routeId+"&search="+searchContent;$.post(url,askdata,function(data){var consul_list=data.consul_list;var consul_pager=data.pager;if(typeof(consul_list)=="undefined"||consul_list==''){$('.all_question').hide();$('#show_no_question').show();}else{$('.all_question').show();$('#show_no_question').hide();document.getElementById("consul_pager").innerHTML=consul_pager;if(consul_pager=="<span class='page-cur'>1</span>"){$('#pagination').hide();}else{$('#pagination').show();}
var list_num=consul_list.length;var li_list=$('.all_question .AQ_ques').find("li");li_list.css("display","none");for(var i=0;i<list_num;i++){cul_tmp=consul_list[i];li_tmp=li_list.eq(i);li_tmp.css("display","");if(cul_tmp.common_flag==1){li_tmp.find('.AQ_left_ask').html('');li_tmp.find('.AQ_left_ask').prepend('<span class="c_icon">常见问题</span>咨询内容:');}else{li_tmp.find('.AQ_left_ask').html('');li_tmp.find('.AQ_left_ask').prepend('<span class="q_icon">咨询内容：</span>');}
li_tmp.find('.a_time').text(cul_tmp.adddate);li_tmp.find('.a_con').text(cul_tmp.answer);li_tmp.find('.a_qst').text(cul_tmp.content);}}},'json');}});$(function(){$('.aq_search_input').focus(function(){var input_val=$(this).val();if(input_val==this.defaultValue){$(this).val('');$(this).removeClass('grey_color');}});$('.aq_search_input').blur(function(){var input_val=$(this).val();if(input_val==''){$(this).addClass('grey_color');$(this).val(this.defaultValue);}})});$("#ask_content").click(function(){tuniuUserCookie=getCookie("tuniuuser");if(tuniuUserCookie==""){pars="ask";show_login(pars,'','');return false;}});$(function(){$("#ask_content").focus(function(){$("#write_question").hide();}).blur(function(){if($("#ask_content").val()==''){$("#write_question").show();}});$("#identify").focus(function(){$("#write_identify").hide();}).blur(function(){if($("#identify").val()==''){$("#write_identify").show();}});});};exports.init=init;window.load_code=load_code;window.getAskByType=getAskByType;window.check_data=check_data;return exports;});;define('tours_page_amd/init_team_page_v2',['jquery','common_amd/tool'],function($,tool){var exports={};function doAddCompare(){$("#addToComp").mouseenter(function(){var isNormal=$(this).hasClass("bg_compare_normal");if(isNormal){$(this).removeClass("bg_compare_normal");$(this).addClass("bg_compare_hover");}}).mouseleave(function(){var isHover=$(this).hasClass("bg_compare_hover");if(isHover){$(this).removeClass("bg_compare_hover");$(this).addClass("bg_compare_normal");}});}
function doAddCollection(){$(document).ready(function(){var url=window.DEBUG?"http://www.tuniu.org/yii.php?r=api/attention/getSingleAttentionInfo":"http://www.tuniu.com/yii.php?r=api/attention/getSingleAttentionInfo";$.ajax({url:url,dataType:"jsonp",jsonp:"callFuc",data:{routeId:$("#route_id_tmp").val()},success:function(data){$("#focus_num").text(data+PageData.focusNum);}});var url2=window.DEBUG?"http://www.tuniu.org/yii.php?r=api/attention/isAttention":"http://www.tuniu.com/yii.php?r=api/attention/isAttention";$.ajax({url:url2,dataType:"jsonp",jsonp:"callFuc",data:{routeId:$("#route_id_tmp").val()},success:function(data){$("#favorite_id").removeClass("bg_focus_normal bg_focus_click");switch(data){case 1:$("#favorite_id").addClass("bg_focus_normal");$("#favorite_id").text("关注");break;case 2:$("#favorite_id").addClass("bg_focus_click");$("#favorite_id").text("已关注");break;case 4:$("#favorite_id").addClass("bg_focus_normal");$("#favorite_id").text("关注");break;}}});});$(window).on("bg_focus_clicked bg_box_foucs_clicked",function(e){var target=$("#focus_num");var offset=$(target).offset();var oneElt=$("<div></div>").addClass("plus_one").css({top:offset.top-$(window).scrollTop(),left:offset.left+(($(target).width()-24)/2)});$(document.body).append(oneElt);$(oneElt).animate({top:"-=30"}).fadeOut(function(){$(oneElt).remove();});});$("#favorite_id").mouseenter(function(){var isNormal=$(this).hasClass("bg_focus_normal");if(isNormal){$(this).removeClass("bg_focus_normal");$(this).addClass("bg_focus_hover");}}).mouseleave(function(){var isHover=$(this).hasClass("bg_focus_hover");if(isHover){$(this).removeClass("bg_focus_hover");$(this).addClass("bg_focus_normal");}});$("#favorite_id").click(function(){var routeId=$("#route_id_tmp").val();if($(this).hasClass("bg_focus_click")){$('#delete_collcet_id').show();$('#collcet_id').hide();return;}
var url=window.DEBUG?"http://www.tuniu.org/yii.php?r=api/attention/attention":"http://www.tuniu.com/yii.php?r=api/attention/attention";var days=$('#journeyDays').val();days=days==null?0:days;$.ajax({url:url,dataType:"jsonp",jsonp:"callFuc",data:{routeId:routeId,days:days,from:"bs3"},success:function(data){alert(data);switch(data){case 1:disClick();$('#collcet_id').show();$('#delete_collcet_id').hide();break;case 2:break;case 3:alert('添加关注失败!');break;case 4:$('#login_id').show();break;}}});});}
function clickAddScroll(){var userId=$("#userId").attr("user_id"),routeId=$("#route_id_tmp").val();if(userId>0){var url="/main.php?do=user_route_collect&flag=collectInsert";var info={userId:userId,routeId:routeId};$.get(url,info,function(data){if(data==1){disClick();$('#collcet_id').show();$('#delete_collcet_id').hide();return;}else if(data==2){$('#delete_collcet_id').show();$('#collcet_id').hide();$(".add_to_favorite").removeClass("on");$(".change_price").children('div').removeClass('change_price_con').css('display','none');$('.start_subscribe').addClass('change_price_con');$('.change_plan_date').addClass('change_price_date');$('.change_price_list .subscribe_info').hide();$('.select_date1').find('.s_con').text('请选择出发日期');$('.select_date2').find('.s_con').text('请选择出发日期');$('.email').val('');return;}else if(data==3){alert('添加收藏失败!');return;}else if(data==4){alert('删除收藏失败!');return;}});}else{$('#login_id').show();return;}}
function request(paras){var url=location.href;var paraString=url.substring(url.indexOf("?")+1,url.length).split("&");var paraObj={}
for(i=0;j=paraString[i];i++){paraObj[j.substring(0,j.indexOf("=")).toLowerCase()]=j.substring(j.indexOf("=")+1,j.length);}
var returnValue=paraObj[paras.toLowerCase()];if(typeof(returnValue)=="undefined"){return"";}else{return returnValue;}}
function disClick(){var addBtn=$("#favorite_id");$(addBtn).trigger("bg_focus_clicked");$(addBtn).removeClass("bg_focus_hover");$(addBtn).addClass("bg_focus_click on");$(addBtn).text("已关注");var value=parseInt($("#focus_num").text());$("#focus_num").text(value+1);if($(addBtn).hasClass("on")){$(".add_scroll").addClass("addbtn");}}
function disUnclick(){var addBtn=$("#favorite_id");$(addBtn).removeClass("bg_focus_click on");$(addBtn).addClass("bg_focus_hover");}
function loadXmlDocRecentOrderInfo(url,func){if(window.XMLHttpRequest){xmlhttpRecentOrders=new XMLHttpRequest();}else{xmlhttpRecentOrders=new ActiveXObject("Microsoft.XMLHTTP");}
xmlhttpRecentOrders.onreadystatechange=func;xmlhttpRecentOrders.open("GET",url,true);xmlhttpRecentOrders.send();}
function mouseAsync(){if(document.getElementById("recent_orders_show")){callBackRecentOrderInfo();}}
var xmlhttpRecentOrders;function callBackRecentOrderInfo(){var routeId=$("#route_id_tmp").val();var empty_tenUsers=$("#empty_tenUsers").val();var urlRecentOrders="/lazy/routeRecentOrder/";urlRecentOrders+=routeId;loadXmlDocRecentOrderInfo(urlRecentOrders,function(){if(xmlhttpRecentOrders.readyState==4&&xmlhttpRecentOrders.status==200){document.getElementById("recent_orders_show").innerHTML=xmlhttpRecentOrders.responseText;if(!empty_tenUsers){if($(".ub_wrap").find("li").length>0){var marquee=new ScrollText("ub_wrap");marquee.LineHeight=30;marquee.Amount=1;marquee.Timeout=1000;marquee.Delay=30;marquee.Start();}}}});}
var init=function(){$('.update_project').each(function(i,n){$(this).hover(function(){$('.update_con').eq(i).toggle(0,function(){$('.update_project').eq(i).toggleClass('update_project_hover');return false;});});});if($('#kind_flag').length>0&&$('#tour_abstruct').length>0){if($('#kind_flag').val()==7){var cont=$.trim($('#tour_abstruct').text());cont=cont.substring(0,cont.length-1);$('#tour_abstruct').text(cont+'（您可在网上预订过程中查看和选择合适的航班出行）。');}}
var cmpId=request('cmpid');var routeId;var noDateStr=$('#no_product').val();var noDate=parseInt(noDateStr,10);var cityCode=$('#city_code').val();var catid=$('#catid').val();if(noDate==1){routeId=$('#route_id_tmp').val();}else{routeId=0;}
if(!cmpId){cmpId=0;}
if(cmpId=='mkt_08009601'||cmpId=='mkt_08009602'||noDate){var data={'key':'recommended','id':catid,'routeid':routeId,'city':cityCode,'type':1,'limit':4,'cmpid':cmpId};$.get('/ajax-default/',data,function(data,status){if(data){$("#noprod_box").html(data);$("#noprod_box").show();}else if(noDate==1){try{var arrPageSizes=___getPageSize();$('#noDate').css({top:parseInt($('#noDate').css("top"))-(arrPageSizes[3]/5)+(arrPageSizes[3]-parseInt($('#noDate').css("height")))/2-10});}catch(e){}
$("#noprod_box").removeClass("mb_10");}else{$("#noprod_box").removeClass("mb_10");}});}
$(document).one('mousemove',mouseAsync);$(function(){$('.pop_box .del').each(function(){$(this).click(function(){$(this).parent().hide();})});var userId=$('#userId').attr("user_id");var myCollectId=$('#myCollectId').attr("my_collect_id");if(userId>0&&myCollectId>0){disClick();}});doAddCollection();doAddCompare();};exports.init=init;return exports;});;define('tours_page_amd/online_ask',['jquery','common_amd/thickbox3.1'],function($,thickbox_mod){var exports={};var tb_show=thickbox_mod.tb_show;function getCookie(c_name){if(document.cookie.length>0){c_start=document.cookie.indexOf(c_name+"=")
if(c_start!=-1){c_start=c_start+c_name.length+1
c_end=document.cookie.indexOf(";",c_start)
if(c_end==-1)c_end=document.cookie.length
return unescape(document.cookie.substring(c_start,c_end))}}
return""}
function getAskByType(page){var type=$("#page_num").val();if(page){curPage=page;}else{curPage=1;}
if($(".aq_search_input").val()!="请输入问题"){searchContent=$(".aq_search_input").val();}else{searchContent='';}
routeId=$('#online_ask_route_id').val();var url="/yii.php?r=knowledgeAsk/index/";var askdata="&page="+curPage+"&type="+type+"&routeId="+routeId+"&search="+searchContent;$.post(url,askdata,function(data){var consul_list=data.consul_list;var consul_pager=data.pager;if(typeof(consul_list)=="undefined"||consul_list==''){$('.all_question').hide();$('#show_no_question').show();}else{$('.all_question').show();$('#show_no_question').hide();document.getElementById("consul_pager").innerHTML=consul_pager;if(consul_pager=="<span class='page-cur'>1</span>"){$('#pagination').hide();}else{$('#pagination').show();}
var list_num=consul_list.length;var li_list=$('.all_question .AQ_ques').find("li");li_list.css("display","none");for(var i=0;i<list_num;i++){cul_tmp=consul_list[i];li_tmp=li_list.eq(i);li_tmp.css("display","");if(cul_tmp.common_flag==1){li_tmp.find('.AQ_left_ask').html('');li_tmp.find('.AQ_left_ask').prepend('<span class="c_icon">常见问题</span>咨询内容:');}else{li_tmp.find('.AQ_left_ask').html('');li_tmp.find('.AQ_left_ask').prepend('<span class="q_icon">咨询内容：</span>');}
var askurl="/asks/";askurl=askurl+cul_tmp.id;li_tmp.find('.a_qst').attr("href",askurl);li_tmp.find('.a_time').text(cul_tmp.adddate);li_tmp.find('.a_con').text(cul_tmp.answer);li_tmp.find('.a_qst').text(cul_tmp.content);}}},'json');}
function show_login(pars,login_func,tel_func){var url="/yii.php?r=quickLogin/index/loginType/";url+=pars;url+="&placeValuesBeforeTB="+'savedValues';url+="&TB_iframe="+true;url+="&height="+250;url+="&width="+650;url+="&modal="+true;tb_show('',url,'');}
function check_data(){tuniuUserCookie=getCookie("tuniuuser");if(tuniuUserCookie==""){pars="ask";show_login(pars,'','');return false;}
var selectRadio=document.getElementsByName("aq_style");for(var i=0;i<selectRadio.length;i++){if(selectRadio[i].checked){question_type=selectRadio[i].value;}}
$("#sub_button").attr('disabled',true);if(typeof(question_type)=="undefined"){document.getElementById("choose_question").style.display="block";$("#sub_button").removeAttr('disabled');return false;}
if(document.getElementById("ask_content").value==""){document.getElementById("write_question").style.display="block";document.getElementById("ask_content").focus();$("#sub_button").removeAttr('disabled');return false;}
if(document.getElementById("email").value!=''){if(document.getElementById("email").value.search(/^\w+((-\w+)|(\.\w+))*\@[A-Za-z0-9]+((\.|-)[A-Za-z0-9]+)*\.[A-Za-z0-9]+$/)==-1){alert("请填写正确邮箱");document.getElementById("email").focus();$("#sub_button").removeAttr('disabled');return false;}}
if(document.getElementById("identify").value==""){document.getElementById("write_identify").style.display="block";document.getElementById("identify").focus();$("#sub_button").removeAttr('disabled');return false;}
var identify=document.getElementById("identify").value;var result=$.get("/main.php?do=user_reg_check_name&identify="+identify+"&flag=single_identify&cache="+Math.random(),function(data){identify_check_result(data)});return false;}
function change_img(){var random=Math.random();var imageCode=$('#identify_img');if(imageCode.length>0){imageCode[0].src='/identify.php?sid='+random;}}
function load_code(){var identify_img=$("#identify_img");if(identify_img.length>0){if(identify_img.css('display')=='none'){identify_img.show();var random=Math.random();identify_img[0].src='/identify.php?sid='+random;}}}
function identify_check_result(result){routeId=$('#online_ask_route_id').val();if(result=='1'){var url='/tours/addask/'+routeId;var user_email=$("#email").val()
if(''==$("#email").val()){user_email=$("#user_email").val();}
var selectRadio=document.getElementsByName("aq_style");for(var i=0;i<selectRadio.length;i++){if(selectRadio[i].checked){question_type=selectRadio[i].value;}}
var info={content:$("#ask_content").val(),email:user_email,identify:$("#identify").val(),question_type:question_type};$.post(url,info,function(data){if(data==-1){alert('验证码填写错误');change_img();$("#sub_button").removeAttr('disabled');}else if(data==-2){alert('问题字数不能超过200字');change_img();$("#sub_button").removeAttr('disabled');}else if(data==-3){alert('请填入问题的内容');change_img();$("#sub_button").removeAttr('disabled');}else if(data==-4){alert('请填入邮箱地址');change_img();$("#sub_button").removeAttr('disabled');}else if(data==0){alert('提交失败，请重试');change_img();$("#sub_button").removeAttr('disabled');}else if(data==1){alert('您的提问已提交成功，感谢您的关注。您的提问我们会在30分钟内回复。\n18:00之后的提问将在次日9：00后回复。您也可以登录会员中心-我的提问中查看您的问题及回复。');$("#sub_button").removeAttr('disabled');$("#ask_content").val('');$("#identify").val('');for(var i=0;i<selectRadio.length;i++){if(selectRadio[i].checked){selectRadio[i].checked=false;}}}});}else{alert('验证码填写错误');change_img();$("#sub_button").removeAttr('disabled');}}
var init=function(){thickbox_mod.init();$(function(){$(".aq_list .cj_pro").click(function(){$(this).addClass("curr").siblings().removeClass("curr");$("#page_num").val("");$("#pagination").hide();$(".all_question .cj_pro").show();$(".all_question .AQ_ques").hide();})
page_pro();function page_pro(){var last_index=1;var pagesLen=$(".cj_pro_page .page_num");pagesLen.click(function(){var i=$(this).index();if(i>1){$(".page_prev").show();}else{$(".page_prev").hide();}
$(this).addClass("page-cur").siblings().removeClass("page-cur");$(".cj_pro li").hide();$(".cj_pro").find("li.page_"+i).show();last_index=i;if(i==4){$(".page_next").hide();}else{$(".page_next").show();}});$(".page_next").click(function(){last_index++;$(".page_prev").show();if(last_index==4){pagesLen.eq(3).addClass("page-cur").siblings().removeClass("page-cur");$(".page_next").hide();$(".cj_pro li").hide();$(".cj_pro").find("li.page_4").show();}else{$(".page_next").show();pagesLen.eq(last_index-1).addClass("page-cur").siblings().removeClass("page-cur");$(".cj_pro li").hide();$(".cj_pro").find("li.page_"+last_index).show();}});$(".page_prev").click(function(){last_index--;$(".page_next").show()
if(last_index==1){pagesLen.eq(0).addClass("page-cur").siblings().removeClass("page-cur");$(".page_prev").hide();$(".cj_pro li").hide();$(".cj_pro").find("li.page_1").show();}else{$(".page_prev").show();pagesLen.eq(last_index-1).addClass("page-cur").siblings().removeClass("page-cur");$(".cj_pro li").hide();$(".cj_pro").find("li.page_"+last_index).show();}});}
$(".aq_list a").bind({click:clickCurr});function clickCurr(){$(".all_question .cj_pro").hide();$(".all_question .AQ_ques").show();$(this).addClass("curr").siblings().removeClass("curr");$("#page_num").val($(this).attr("value"));var type=$("#page_num").val();var curPage=1;if($(".aq_search_input").val()!="请输入问题"){searchContent=$(".aq_search_input").val();}else{searchContent='';}
routeId=$('#online_ask_route_id').val();var url="/yii.php?r=knowledgeAsk/index/";var askdata="&page="+curPage+"&type="+type+"&routeId="+routeId+"&search="+searchContent;$.post(url,askdata,function(data){var consul_list=data.consul_list;var consul_pager=data.pager;if(typeof(consul_list)=="undefined"||consul_list==''){$('.all_question').hide();$('#show_no_question').show();}else{$('.all_question').show();$('#show_no_question').hide();document.getElementById("consul_pager").innerHTML=consul_pager;if(consul_pager=="<span class='page-cur'>1</span>"){$('#pagination').hide();}else{$('#pagination').show();}
var list_num=consul_list.length;var li_list=$('.all_question .AQ_ques').find("li");li_list.css("display","none");for(var i=0;i<list_num;i++){cul_tmp=consul_list[i];li_tmp=li_list.eq(i);li_tmp.css("display","");if(cul_tmp.common_flag==1){li_tmp.find('.AQ_left_ask').html('');li_tmp.find('.AQ_left_ask').prepend('<span class="c_icon">常见问题</span>咨询内容:');}else{li_tmp.find('.AQ_left_ask').html('');li_tmp.find('.AQ_left_ask').prepend('<span class="q_icon">咨询内容：</span>');}
li_tmp.find('.a_time').text(cul_tmp.adddate);li_tmp.find('.a_con').text(cul_tmp.answer);li_tmp.find('.a_qst').text(cul_tmp.content);}}},'json');}});$(function(){$('.aq_search_input').focus(function(){var input_val=$(this).val();if(input_val==this.defaultValue){$(this).val('');$(this).removeClass('grey_color');}});$('.aq_search_input').blur(function(){var input_val=$(this).val();if(input_val==''){$(this).addClass('grey_color');$(this).val(this.defaultValue);}})});$("#ask_content").click(function(){tuniuUserCookie=getCookie("tuniuuser");if(tuniuUserCookie==""){pars="ask";show_login(pars,'','');return false;}});$(function(){$("#ask_content").focus(function(){$("#write_question").hide();}).blur(function(){if($("#ask_content").val()==''){$("#write_question").show();}});$("#identify").focus(function(){$("#write_identify").hide();}).blur(function(){if($("#identify").val()==''){$("#write_identify").show();}});});};exports.init=init;window.load_code=load_code;window.getAskByType=getAskByType;window.check_data=check_data;return exports;});;define('tours_page_amd/change_price_notice',['jquery'],function($){var exports={};function check_email(email){if(email!=''){var patrn=/^\w+((-\w+)|(\.\w+))*\@[A-Za-z0-9]+((\.|-)[A-Za-z0-9]+)*\.[A-Za-z0-9]+$/;if(!patrn.exec(email)){return 3;}}else{return 2;}
return 1;}
function mail_check(email){var email=$('.email').val();if(check_email(email)!=1){$('.c_err').html('请输入有效的Email地址');$('.c_err').parent('.c_item').show();return false;}else{if($('.c_err').html()=='请输入有效的Email地址'){$('.c_err').html('');return true;}}}
function check_date(){var startTime=$.trim($('.select_date1').find('.s_con').text());var endTime=$.trim($('.select_date2').find('.s_con').text());if(startTime!='请选择出发日期'&&endTime!='请选择出发日期'){if($('.c_err').html()=='请选择最早/最迟出发日期'){$('.c_err').html('');$('.c_err').parent('.c_item').hide();}
if(startTime.length>0&&endTime.length>0){var arr1=startTime.split("-");var arr2=endTime.split("-");var date1=new Date(parseInt(arr1[0]),parseInt(arr1[1])-1,parseInt(arr1[2]),0,0,0);var date2=new Date(parseInt(arr2[0]),parseInt(arr2[1])-1,parseInt(arr2[2]),0,0,0);if(date1.getTime()>date2.getTime()){$('.c_err').html('最迟出发日期需在最早出发日期之后');$('.c_err').parent('.c_item').show();return false;}else{if($('.c_err').html()=='最迟出发日期需在最早出发日期之后'){$('.c_err').html('');$('.c_err').parent('.c_item').hide();}
var total_day=Math.abs((date1.getTime()-date2.getTime()))/(1000*60*60*24);if(total_day>60){$('.c_err').html('时间跨度不能超过两个月');$('.c_err').parent('.c_item').show();}else{if($('.c_err').html()=='时间跨度不能超过两个月'){$('.c_err').html('');$('.c_err').parent('.c_item').hide();}
var userId=$('#userId').val();var productId=$('#route_id_tmp').val();var email=$('.email').val();var myCollectId=$('#myCollectId').val();mail_check(email);if($('.c_err').text()!=''){return false;}
if($.trim($('.c_err').html()).length==0){$('.c_err').parent('.c_item').hide();}
$('.c_submit').parent('.c_item').hide();$('.c_tijiao').parent('.c_item').show();$('.c_tijiao').css('cursor','default');if(myCollectId.length==0){var url_1="/main.php?do=user_route_collect&flag=collectInsert";var info_1={userId:userId,routeId:productId};$.get(url_1,info_1,function(data){if(data==1){$('#favorite_id').addClass('on');return true;}else{return false;}});}
var url="/yii.php?r=tours/subscribe";var info={userId:userId,productId:productId,email:email,startTime:startTime,endTime:endTime};$.post(url,info,function(data){$('.c_tijiao').parent('.c_item').hide();$('.c_submit').parent('.c_item').show();$('.change_plan_date').hide();$('.change_plan_date').removeClass('change_price_con');if(data==1){$('.r_err .start_time').text(startTime);$('.r_err .end_time').text(endTime);$('.r_err').parent('.c_item').show();$('.change_price_con_succ').show();$('.change_price_con_fail').hide();setTimeout("$('.change_price_con_succ').hide();$('.change_plan_date').addClass('change_price_con');$('.start_subscribe').hide();",10000);return true;}else{$('.change_price_con_fail').show();$('.change_price_con_succ').hide();return false;}});}
return false;}}}else{$('.c_err').html('请选择最早/最迟出发日期');$('.c_err').parent('.c_item').show();return false;}}
var init=function(){var user_id=$('#userId').val();var user_email=$('#user_email').val();var subscribe_num=$('#subscribe_num').val();var subscirbe_email=$('#subscirbe_email').val();var subscirbe_id=$('#subscirbe_id').val();var subscirbe_start_time=$('#subscirbe_start_time').val();var subscirbe_end_time=$('#subscirbe_end_time').val();if(!user_id||user_id==0||user_id=="undefined"){$('.change_price .pop_login').removeClass('change_price_date').addClass('change_price_con');}else{if(subscirbe_id==''||subscirbe_id=="undefined"){if(subscribe_num>9){$('.over_ten').removeClass('change_price_date').addClass('change_price_con');}else{$('.start_subscribe').removeClass('change_price_date').addClass('change_price_con');$('.change_plan_date').addClass('change_price_date');}}else{$('.change_plan_date').show();$('.r_err').parent('.c_item').show();$('.email').val(subscirbe_email);$('.subscribe_info .start_time').text(subscirbe_start_time);$('.subscribe_info .end_time').text(subscirbe_end_time);$('.select_date1 .start_time').html(subscirbe_start_time);$('.select_date2 .end_time').html(subscirbe_end_time);$('.change_plan_date').removeClass('change_price_date').addClass('change_price_con');}}
$('.order_price_mail').click(function(){$('.change_price_con').hide();$('.change_plan_date').show();$('.c_submit').removeClass('c_tijiao');})
$('.change_price_con_succ .c_close').click(function(){$('.change_price_con_succ').hide();$('.start_subscribe').hide();$('.change_plan_date').addClass('change_price_con');})
$('.change_plan_date .c_cancle').click(function(){$('.change_plan_date').hide();})
$('.change_price_con_fail .c_cancle').click(function(){$('.change_price_con_fail').hide();$('.change_plan_date').addClass('change_price_con');$('.start_subscribe').hide();})
$('.c_submit').click(function(){check_date();})
if($.trim($('.c_err').html()).length==0){$('.c_err').parent('.c_item').hide();}};exports.init=init;return exports;});