define('product/city_search',['jquery','underscore','product/jquery.pkgautocomplete'],function($,_){var cities={};var currentInputs={};var defaultOption={id:'J_Cities',cityUrl:'/yii.php?r=dynamic/ajaxGetCity',onChange:function(){},onError:function(){}};$.fn.citysearch=function(option){return this.each(function(){var textBox=$(this);var cityiesEle,tabEles,boxEles;var config=$.extend({},defaultOption,option);cityiesEle=$('#'+config.id).clone();cityiesEle.removeAttr('id').hide().appendTo('body');tabEles=$(".cities_cat li",cityiesEle);boxEles=$(".cities_list_cat",cityiesEle);function isParent(child,parent){var parents=child.parents();var res=false;if(child[0]===parent){res=true;}else{parents.each(function(){if(this===parent){res=true;return false;}});}
return res;}
function bindCitySearch(textBox,layer){var lowerIE=$.browser.msie&&$.browser.version<='8.0';var blurByLayer=false;if(lowerIE){textBox.focus(function(){showBox();}).blur(function(e){if(blurByLayer){e.preventDefault();e.stopPropagation();blurByLayer=false;}else{hideBox();}});layer.bind('mousedown',function(){blurByLayer=true;});$(document).mousedown(function(e){if(isParent($(e.target),layer[0])||e.target===textBox[0]){textBox.focus();}else{hideBox();}});}else{textBox.focus(function(){this.focused=true;this.select();showBox();}).mouseup(function(){if(this.focused){this.focused=false;return false;}}).blur(function(){hideBox();});layer.bind('mousedown',function(e){e.preventDefault();e.stopPropagation();});}
textBox.bind('change input propertychange',function(e){if(e.type!=='change'&&e.type!=='input'&&!(e.type==='propertychange'&&e.originalEvent.propertyName==='value')){return;}
if(textBox.val()!==''){hideBox();}else{showBox();}});}
function showBox(){var offset=textBox.offset();offset.height=textBox.outerHeight();_.each(cities,function(city){city.hide();});if(offset){cityiesEle.css({"left":offset.left,"top":offset.top+offset.height}).show();}}
function hideBox(){cityiesEle.hide();}
function setCity(cityCode,cityName){textBox.attr('code',cityCode);textBox.val(cityName);config.onChange({code:cityCode,name:cityName},0);textBox.blur();}
$(window).resize(function(){if(cityiesEle.is(':visible')){setTimeout(showBox,30);}});cityiesEle.delegate(".cities_list a",'click',function(){var code=$(this).attr('code');var cityName=$(this).text();setCity(code,cityName);hideBox();});tabEles.click(function(){var tab=$(this);var index=tab.index();tabEles.removeClass("current");tab.addClass("current");boxEles.addClass('hide').hide();$(boxEles.get(index)).show().removeClass('hide');});bindCitySearch(textBox,cityiesEle);var autocompleteOption={autoSelectFirst:false,showNoSuggestionNotice:true,noSuggestionNotice:'找不到相关的城市',width:textBox.outerWidth(),onFocus:function(){},onSearchStart:function(){if(this.value&&this.getAttribute('code')){return false;}else{hideBox();}},beforeRender:function(){hideBox();},onSelect:function(suggestion){textBox.attr('code',suggestion.cityCode);config.onChange(suggestion,1);},onHint:function(hint){},onInvalidateSelection:function(){}};var op=$.extend({},config.autocompleteOption,autocompleteOption);if(config.cityUrl){op.serviceUrl=config.cityUrl;}
textBox.bind('keydown',function(e){if(e.keyCode!=9&&e.keyCode!=13){textBox.removeAttr('code');hideBox();}}).pkgautocomplete(op);});};});